"""
Test script for Rust scanner (cargo-audit + cargo-clippy)
"""
import asyncio
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.scanners.rust_scanner import RustScanner


async def test_rust():
    """Test Rust scanner"""
    print("=" * 60)
    print("Testing Rust Scanner")
    print("=" * 60)
    
    scanner = RustScanner()
    
    # Create a temporary vulnerable Rust project for testing
    test_dir = "tests/test_samples/rust"
    os.makedirs(f"{test_dir}/src", exist_ok=True)
    
    vulnerable_rust = """fn main() {
    // Security issue: unwrap can panic
    let value = Some(42);
    let unwrapped = value.unwrap();
    
    // Security issue: expect can panic
    let result: Result<i32, &str> = Ok(10);
    let expected = result.expect("Failed");
    
    // Security issue: unimplemented
    let _x = unimplemented!();
    
    println!("Vulnerable Rust code: {}", unwrapped);
}
"""
    
    with open(f"{test_dir}/src/main.rs", "w") as f:
        f.write(vulnerable_rust)
    
    # Create Cargo.toml
    cargo_toml = """[package]
name = "vulnerable-rust-test"
version = "0.1.0"
edition = "2021"

[dependencies]
"""
    
    with open(f"{test_dir}/Cargo.toml", "w") as f:
        f.write(cargo_toml)
    
    # Create Cargo.lock (empty for now)
    with open(f"{test_dir}/Cargo.lock", "w") as f:
        f.write("# This file is automatically generated by Cargo.\n")
    
    results = await scanner.scan(test_dir)
    
    print(f"\nFound {len(results)} issues:")
    for i, finding in enumerate(results, 1):
        print(f"\n{i}. [{finding['severity']}] {finding['tool']}:{finding['rule_id']}")
        print(f"   File: {finding['file']}:{finding['line']}")
        print(f"   Description: {finding['description']}")
    
    return results


async def main():
    """Run all tests"""
    rust_results = await test_rust()
    
    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"Rust findings: {len(rust_results)}")
    
    if rust_results:
        print("\n✅ Rust scanner is working correctly!")
        return 0
    else:
        print("\n⚠️  No findings detected. Check scanner configuration.")
        return 1


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
